import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { ArrowLeft, Box, CheckCircle2, MapPin, Truck } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { OutreachService } from '../services/outreach';
import FeatureGate from '../components/FeatureGate';
const c = { bg: '#0B0F19', card: '#151B2B', border: '#1E293B', text: '#E2E8F0', muted: '#94A3B8', cyan: '#00F0FF', green: '#10B981', amber: '#F59E0B' };
export default function ShipmentsScreen() { const navigation = useNavigation<any>(); const [shipments, setShipments] = useState<any[]>([]); const [loading, setLoading] = useState(true); const load = useCallback(async () => { try { setShipments((await OutreachService.getShipments()).shipments || []); } finally { setLoading(false); } }, []); useFocusEffect(useCallback(() => { load(); }, [load])); const confirm = (id: string) => Alert.alert('Confirm pickup', 'Has the dispatch company collected this product?', [{ text: 'Cancel', style: 'cancel' }, { text: 'Confirm', onPress: async () => { try { await OutreachService.confirmPickup(id); load(); } catch (e: any) { Alert.alert('Could not update shipment', e.message); } } }]); return <FeatureGate flag="shipping_ui" message="This area is currently unavailable."><SafeAreaView style={styles.safe} edges={['top']}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><ArrowLeft color={c.text} size={22} /></TouchableOpacity><Text style={styles.title}>Orders & Shipping</Text><Truck color={c.cyan} size={20} /></View>{loading ? <ActivityIndicator color={c.cyan} style={{ marginTop: 40 }} /> : <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={c.cyan} />}><Text style={styles.subtitle}>Track physical-product dispatch and delivery progress.</Text>{shipments.length === 0 ? <View style={styles.empty}><Box color={c.muted} size={30} /><Text style={styles.muted}>No shipments yet</Text></View> : shipments.map(s => <View key={s.id} style={styles.card}><View style={styles.row}><View style={styles.icon}><Truck color={c.cyan} size={19} /></View><View style={{ flex: 1 }}><Text style={styles.status}>{String(s.status || 'awaiting_dispatch').replace(/_/g, ' ')}</Text><Text style={styles.meta}>{s.carrier || 'Carrier pending'}{s.tracking_number ? ` · ${s.tracking_number}` : ''}</Text></View></View><View style={styles.line}><MapPin color={c.muted} size={15} /><Text style={styles.address}>{s.pickup_address || 'Pickup address pending'}</Text></View>{Array.isArray(s.tracking_events) && s.tracking_events.length > 0 && <View style={styles.event}><CheckCircle2 color={c.green} size={15} /><Text style={styles.meta}>{s.tracking_events[s.tracking_events.length - 1].status}</Text></View>}{s.status === 'awaiting_dispatch' && <TouchableOpacity style={styles.button} onPress={() => confirm(s.id)}><Text style={styles.buttonText}>Confirm pickup</Text></TouchableOpacity>}</View>)}</ScrollView>}</SafeAreaView></FeatureGate>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: c.bg }, header: { height: 64, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 16, borderBottomWidth: 1, borderBottomColor: c.border }, title: { flex: 1, color: c.text, fontSize: 20, fontWeight: '800' }, content: { padding: 16, paddingBottom: 40 }, subtitle: { color: c.muted, marginBottom: 16 }, card: { backgroundColor: c.card, borderWidth: 1, borderColor: c.border, borderRadius: 14, padding: 15, marginBottom: 10 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, icon: { width: 38, height: 38, borderRadius: 11, backgroundColor: `${c.cyan}15`, alignItems: 'center', justifyContent: 'center' }, status: { color: c.text, fontWeight: '800', textTransform: 'capitalize' }, meta: { color: c.muted, fontSize: 12, marginTop: 3 }, line: { flexDirection: 'row', gap: 8, marginTop: 14 }, address: { color: c.text, flex: 1 }, event: { flexDirection: 'row', gap: 8, marginTop: 12, alignItems: 'center' }, button: { marginTop: 15, padding: 12, borderRadius: 10, backgroundColor: c.cyan, alignItems: 'center' }, buttonText: { color: '#04121A', fontWeight: '800' }, empty: { alignItems: 'center', paddingTop: 80, gap: 10 }, muted: { color: c.muted } });
